apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment
 labels:
  author: seshu
  type: frontend
spec:
 replicas: 3
 selector:
  matchLabels:
   tier: frontend
 template:
  metadata:
   name: nginx-pod
   labels:
    tier: frontend
  spec:
   containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
       - containerPort: 80
         hostPort: 8899
  
