apiVersion: v1
kind: Pod
metadata: 
 name: third-pod
 labels:
  author: seshu
  type: backend-database
spec:
 containers:
  - name: mydb
    image: mysql:5
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: seshu
