apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: first-replicaset
 labels:
  author: seshu
  type: frontend
spec:
 replicas: 3
 selector:
  matchLabels:
   tier: frontend
 template:
  metadata:
   name: appserver
   labels:
    tier: frontend
  spec:
   containers:
    - name: appserver
      image: httpd

